language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"
  - "nightly"

install:
  - pip install -U pip
  - pip install "pillow<4.0.0"
  - pip install -e .

script: pytest --verbose
